### ISSUE TITLE
[Feature] App: Import/Export a configuration file that contains repository addresses

### ISSUE THREAD

**Issue by ccho-mongodb** [dacharyc/prfocus-website#12]
**Is your feature request related to a problem? Please describe.**
What problem would this feature solve? Ex. I'm always frustrated when [...]
Currently, I was only able to locate a feature to add individual repository addresses. It took some time to add all the ones I wanted due to the single-entry interface. If my team members wanted to use the tool, they would have to spend time doing the same task.

**Describe the solution you'd like**
Tell me what you'd like to see happen when the above problem occurs!
Allow import/export of a configuration file (or perhaps a text field?) that contains a list of repository addresses so that users don't have to individually add repositories.

**Describe alternatives you've considered**
Is there something else that might make sense, instead?

**Additional context**
Is this related to a specific workflow that your organization or repository uses? If so, please tell me more about your workflow to help me understand your request.

**Labels**
Let me know whether your feature is related to the PR Focus app or website. I've pre-selected the app for your convenience, but please remove the app label and change it to website, instead, if your suggestion is for the website.

**Comment by dacharyc** [comment]
Thank you for suggesting this enhancement! This seems like a nice quality-of-life improvement I should be able to implement in a  relatively short timeframe. I'll allocate this to next week's build, and will update here if I need to bump it out to a later version.

**Comment by dacharyc** [comment]
Alrighty, I've added the ability to import multiple repositories as a simple text box that takes one URL per line. If your team has a list of repository addresses, this should enable adding multiple repositories in one operation.

<img width="341" alt="Screenshot 2023-09-16 at 9 44 12 PM" src="https://github.com/dacharyc/prfocus-website/assets/1308377/98010195-4851-4778-9c1e-014d5d5fadff">

This will be in the release that comes out on Monday.

Thanks for the suggestion!
