### ISSUE TITLE
[Feature] app - log trimming features

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#13]
- logs should have a maximum number of entries
- It would be nice if there was a "clear" button when viewing the logs that deleted all of the existing logs so that I could focus on logs related to a specific operation

**Comment by dacharyc** [comment]
Thanks for suggesting this enhancement! I've added a button to clear log entries, and I've added the functionality to automatically delete log entries more than a day old. These new features should be in the next build, which I'm hoping to release on Monday.
