### ISSUE TITLE
[Feature] ability to go directly to GitHub without clicking into details.

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#15]
As a user, I want to be able to go to the PR on GitHub _without_ having to first click into the details, and then find the small link to go to GItHub. 

## Desired Behavior
button / link / right-click menu option on the list screen entry that i can click/choose and be taken directly to the PR in GitHub. 

> Is there something else that might make sense, instead?
keyboard navigation + key combo to launch, but that'd be a LOT more work and not help mouse-centric users.

**Comment by dacharyc** [comment]
Thanks for the request! I've added this functionality to the upcoming build, which I hope to release this coming Monday.
