### ISSUE TITLE
[Feature] app: big-ol-button for view on github

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#20]
as a user i want the mechanism to view the ticket on github to be very obvious and easy to click. 

For me the "View PR on GitHub" link feels like it's just another part of the large quantity of information being displayed to me instead of something that says "HEY CLICK ME!" 

**Describe the solution you'd like**
add a button to view on github in the row by the Watch and Ignore buttons (preferably with a bit of separation since they're conceptually different).

**Describe alternatives you've considered**

- replacing current text with button in the same place
- adding icon by text
- changing text color

none of these seem as good. the watch and ignore button are already obvious calls to action and thus i'm already primed for "clicky things live here" in that area of the display.

**Comment by dacharyc** [comment]
After talking it through offline, I've added a larger callout in the title row, and I'm also now using the same callout consistently everywhere in the detail view where I link out to GitHub.

<img width="1318" alt="new-link-style" src="https://github.com/dacharyc/prfocus-website/assets/1308377/bb323962-b09e-4112-929d-6b4afffcc59d">

I do think this makes for more consistent UX, and I hope this solves your desire for a more obvious GitHub link. This will be included in the next release, which I hope to release this weekend. Thanks for the suggestion!
