### ISSUE TITLE
[Feature] App: Bulk operations on PRs

### ISSUE THREAD

**Issue by cbullinger** [dacharyc/prfocus-website#25]
As a new user adding multiple active repos, I found it very tedious to sift through the fetched PRs. It'd be nice to bulk select PRs and take an action (i.e. ignore or watch) instead of handling each one individually.

**Comment by dacharyc** [comment]
Thank you - this was a great feature request! I've added the ability to perform bulk actions from the aggregate Inbox. (Watch, Ignore, Archive.) You can find this new functionality in version 0.7.

I appreciate the request!
