### ISSUE TITLE
[Bug] App - overly picky url validation

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#3]
**Describe the bug**

## expected behavior
as a user i expect PR Focus to accept repo urls with trailing slashes when adding a new repository. 

## actual behavior
url validation raises an error when adding an url for a repo that ends in a trailing slash. it should just accept it. This happens in the onboarding flow and when manually adding an url later.

example of url it complains about: 

```
https://github.com/masukomi/mongodb_meilisearch/
```

works fine if you remove the trailing slash.

**Comment by dacharyc** [comment]
Thank you for reporting this! I've fixed it in the next build, which I'm scheduling for release next Monday.
