### ISSUE TITLE
[Feature] App: Filters for PRs to always ignore

### ISSUE THREAD

**Issue by cbullinger** [dacharyc/prfocus-website#30]
As a user who watches repos with recurring automated PRs that I always ignore, I would like to define a filter that tells PR Focus to automatically ignore fetched PRs that meet the criteria. 

For example, it'd be handy to automatically ignore PRs for recurring internal upgrades I don't and won't ever care about. 

This could potentially include filtering for PRs to automatically watch (e.g. for a feature `Foo` with work spanning several of my watched repos, I might want to filter for and watch PRs with `Foo` in the description), but the main ask here is the ability to filter PR "spam".

**Comment by dacharyc** [comment]
Thank you for the suggestion, @cbullinger  - this sounds like a super useful feature request! I'm going to have to give this one some thought about how best to build it. I'm trying to avoid adding new features right at this moment - I'm focusing on bug fixes and maybe a few tiny features for the v1 release candidate. But I would definitely like to implement this after the v1 release.

I will keep you posted when I get to this!

**Comment by dacharyc** [comment]
Filters are now live in PR Focus v1.1.0! It may take some time to distribute across the App Store, but you should be able to see it soon and update to this version.

I've posted an announcement here summarizing the new features, with links to the documentation: https://prfocus.app/news/2024/08/12/introducing-tags-and-filtering-in-pr-focus/

Let me know if this works the way you expect!

**Comment by cbullinger** [comment]
This is great, @dacharyc! Thank you again for the quick responses to my requests and for providing docs with the new features.

Really excited to play around with this! And I love that you tied it in with the new tagging functionality -- super useful. (So does the "Mark as Important". I'm interested to see what that feature looks like whenever it becomes available!)

**Comment by dacharyc** [comment]
This release has been out for a bit, so I'm going to assume no news is good news and go ahead and close this issue. If you find this isn't working the way you expect, please feel free to re-open!

And thank you again for taking the time to suggest a feature - once again, you've made a great suggestion and now that I have it, I can't imagine the app without it!
