### ISSUE TITLE
[Feature] App: Alternative method to select a PR from dashboard

### ISSUE THREAD

**Issue by cbullinger** [dacharyc/prfocus-website#31]
When I'm in the dashboard view, I often accidentally click on a PR, and then have to navigate back from the PR's detail page. I would like a way to change how I select PRs from the dashboard.

Perhaps an optional Settings preference to change the default behavior, e.g.  
- Instead of the default "single-click to view the PR details", you can choose to single-click to "select"/highlight the PR and double-click to view PR details?
- To view the PR details, you must select the PR first (i.e. single-click selects/highlights, the single-click on a selected PR opens the detail view)? 
- Disable "single-click to view details" and use a "View PR" context menu action? 
- Make only a specific part of the PR dashboard card clickable?

**Comment by dacharyc** [comment]
Thanks for this suggestion, @cbullinger ! I should be able to add an optional setting to enable this. I think it should be an equal amount of work to either require a double click to view PR details, or require using a "View PR" context menu option. Do you have a preference between those two options?

**Comment by cbullinger** [comment]
Excellent! Thanks, @dacharyc! 

🤔 My immediate answer was double-click, but after miming it for a few mins in the app, I think the context menu option would be a better experience (for me, anyway).

**Comment by dacharyc** [comment]
Ok! I'll try to sneak this into the 1.0 RC build I'm hoping to release this weekend. I'll update here if it makes it into the build. If not, it'll be a fast follow post 1.0, hopefully. 🤞

**Comment by dacharyc** [comment]
Ok, it's in! There is now a new setting in the PR Focus -> Settings menu called "Right-click to view PR details". When you select and save this setting, the "default" behavior of clicking a PR Summary to view PR Details is no longer available. Instead, you can right click to open the context menu, and there's a new option to View PR Details. That option is not available in the context menu unless you're overriding the default click to view behavior.

This is now in the 1.0 release candidate build that I'll be submitting to App Store Review this weekend, so it should be available for you to test next week, assuming there are no delays with App Review. 🤞 

<img width="445" alt="Screenshot 2024-07-20 at 6 25 37 PM" src="https://github.com/user-attachments/assets/602cee75-b13d-424c-aee2-584263d2c292">
<img width="183" alt="Screenshot 2024-07-20 at 6 26 20 PM" src="https://github.com/user-attachments/assets/0255a2cf-0015-48a5-91f9-37d8cc0db25d">

**Comment by cbullinger** [comment]
You're awesome! Very excited to try this out!! ❤️

**Comment by dacharyc** [comment]
This is in the v0.10 build I have made available to the private beta group! Let me know if you have any problems or if it's working the way you expect.

(Oh, also, I snuck in some improvements to the "Settings" view to make way for some updates I have planned for after v1.0, so you will now find this setting under PR Focus -> Settings -> Accessibility.)

**Comment by dacharyc** [comment]
Have confirmed with you offline that you've been able to test this and it seems to meet your need, so I'm going to go ahead and close this request. Feel free to re-open if you notice any issues or have any additional feedback!
