### ISSUE TITLE
[Bug] app - no success banner when updating API key

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#4]
## Expected Behavior
As a user I expect PR Focus to provide me with some sort of feedback when I have successfully updated configuration data.

## Actual Behavior
there was no indication of success after i successfully updated my API token

**Comment by dacharyc** [comment]
Thank you for reporting this! I recently added code that validated the API key and reported an issue if the process failed, but I forgot to add a success banner. I've fixed this in the upcoming build which should be released next Monday.
