### ISSUE TITLE
[Feature] app - confusing User Profile URL things

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#5]
## Expected Behavior
As a user I expect PR Focus to not need me to specify my User Profile Url because it can get it from the API

## Actual Behavior 
There's a User Profile URL field that has placeholder text.

I am confused by the fact that it's not filled in (because it could get that from the API) and the fact that it exists at all. I don't know why it would be meaningful to me or the app to specify this data.

**Comment by dacharyc** [comment]
Thank you for reporting this! This was a legacy field from very early alpha where the user profile was not queried from the GitHub API access token, but was instead manually provided by the user. This wasn't serving any purpose any longer, and you're right - it was definitely confusing. I've removed this from the view in the next build, which I'm hoping to release next Monday.
