### ISSUE TITLE
[Feature] app - onboarding screen & docs don't specify that it must be a classic API token

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#7]
it should be made clear to users that PR Focus requires a "Classic" GitHub API token to function.

I'd recommend using the following link to take people to the classic form with the required permissions pre-checked, so as to avoid any stumbles

<https://github.com/settings/tokens/new?description=PR%20Focus&scopes=repo,read:user,read>

instructions on how to create 👆 [were found here](https://dev.to/dakdevs/conveniently-link-to-a-pre-filled-new-github-personal-access-token-page-dn)

**Comment by dacharyc** [comment]
Thank you for reporting issues with fine-grained access tokens! I've updated the PR Focus documentation with the required permissions for both fine-grained and classic access tokens: https://prfocus.app/docs/getting-started/#generate-a-github-access-token

I'll update the link in the PR Focus UI to take users to the PR Focus documentation to find out what permissions are required for each token type. That update should be in the next build.

In a future version, I'll provide better handling of authentication errors to surface to users which permissions were missing from their API access tokens. 

I won't be adding a constructed link to pre-fill the classic form with the required permissions pre-checked. I would prefer that PR Focus users use the more restrictive fine-grained token for security reasons. I wasn't able to find a way to pre-fill those permissions. Even if I could, I would prefer users understand what permissions PR Focus needs so they can make an informed decision about whether they want to use it. If I pre-select the right permissions, many people won't bother to read the selections and so can't make an informed decision about using the app.

I very much appreciate your suggestion, and thank you for letting me know you had issues!
